### ISSUE TITLE
New boxes in Capabilities screen?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#456] opened 2022-06-02 19:22 UTC
These checkboxes are a good idea, but when I click on them they add X

Should they add a checkmark instead?
<img width="1020" alt="Screen Shot 2022-06-02 at 3 20 00 PM" src="https://user-images.githubusercontent.com/3868028/171720863-e33e0dd6-0ed4-465c-a6e8-a1a44700758c.png">

**Comment by olatechpro** [comment] 2022-06-02 19:27
@stevejburge isn't that what you requested here https://github.com/publishpress/PublishPress-Capabilities/issues/419?

To rotate between 'X', 'checked', and 'blank'? 

The reason the box didn't mark as checked after clicking is to bring people awareness to it been multiple toggle option

**Comment by agapetry** [comment] 2022-06-02 19:27
@stevejburge They are a way to toggle from unassigned to assigned to blocked.

@olatechpro I think the problem is these need to cycle to checked first.  Sorry, I didn't notice that in my testing but Steve's right, this could lead to a lot of confusion.

**Comment by olatechpro** [comment] 2022-06-02 19:29
Now, here's the problem, the button toggle between 3 action. So, making it checked and uncheck will lead to further confusion and may never know how it rotate and that's my intention for not making it check so it can be clicked further but if that will work, i'll make it check and uncheck based on click. @stevejburge @agapetry

**Comment by agapetry** [comment] 2022-06-02 19:49
I just meant that the order for the cycler should be:

Checked
Unchecked
Blocked (X)

**Comment by olatechpro** [comment] 2022-06-02 19:52
Okay, understood @agapetry .

@stevejburge is that what you mean as well or you're implying for the clicked box beside post to be checked and unchecked based on click?

**Comment by stevejburge** [comment] 2022-06-03 15:24
Thanks @agapetry @olatechpro 

This makes sense to me:

    Checked
    Unchecked
    Blocked (X)

**Closed** 2022-06-06 12:21 UTC
Labels: discussion needed
