### ISSUE TITLE
Improve the design of the main Capabilities screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#32] opened 2020-03-09 15:00 UTC
The Members plugin has an approach that's much cleaner and easier to navigate
https://wordpress.org/plugins/members/

<img width="731" alt="Screen Shot 2020-03-09 at 10 56 55 AM" src="https://user-images.githubusercontent.com/3868028/76226814-c7c96300-61f4-11ea-8c15-6a72283f623b.png">

We need to improve the layout, and also the checkboxes. It's not easy to understand or use the 3. options:

- Green check
- Red X
- Empty
<img width="402" alt="Screen Shot 2020-03-09 at 10 58 49 AM" src="https://user-images.githubusercontent.com/3868028/76227069-1b3bb100-61f5-11ea-8350-483cba2e1c7c.png">

**Comment by stevejburge** [comment] 2020-03-09 15:10
One idea from Joomla:

- Choose the role from a dropdown on the top
- Search box on top
- Icon explanation box in the sidebar

<img width="968" alt="Screen Shot 2020-03-09 at 11 08 01 AM" src="https://user-images.githubusercontent.com/3868028/76227870-54c0ec00-61f6-11ea-9b3d-24d7f915965e.png">

**Comment by agapetry** [comment] 2020-03-09 15:29
I like that approach.  It seems visually clearer and cleaner than separate Approve / Deny checkboxes.

**Comment by stevejburge** [comment] 2020-03-09 15:32
Thanks @agapetry. With PublishPress Capabilities, what are the icons we'll need?

The Joomla approach needs more icons as it has a more confusing system with cascading permissions (hence the "inherited" options)

**Comment by agapetry** [comment] 2020-03-09 15:40
As it stands, we would need:

- Not Allowed (Not Set)
- Denied
- Allowed

I would like to review the "Invalid Capabilities" section. It may make more sense to leave those in other sections, but use a "Conflict" icon.

If we go ahead with the role hierarchy feature, that would create a need for the "Inherited" icons.

So there is a potential application for all six.

**Comment by stevejburge** [comment] 2020-03-09 15:43
@agapetry Thanks

I was thinking "Invalid Capabilities" could be toggled on/off with a setting: https://github.com/publishpress/PublishPress-Capabilities/issues/31

The extra complexity sounds like a good reason to wait on adding role hierarchy

**Comment by htmgarcia** [comment] 2020-03-11 01:22
@agapetry this means "denied", correct?
<img width="146" alt="Screen Shot 2020-03-11 at 10 21 52" src="https://user-images.githubusercontent.com/4999794/76372880-2f60e900-6382-11ea-8852-4828288cc5bb.png">

**Comment by agapetry** [comment] 2020-03-11 01:26
@htmgarcia Yes, that's correct. With the redesign, keep in mind that explicit capability denial is not the typical usage. It's much more common for capabilities to be either enabled or not set.

**Comment by htmgarcia** [comment] 2020-03-20 15:45
Current progress:
![screencapture-localhost-8888-wp-wp-admin-admin-php-2020-03-21-00_43_21](https://user-images.githubusercontent.com/4999794/77180437-42f01a80-6b0d-11ea-9e6b-3aeae31091f0.png)

**Comment by stevejburge** [comment] 2020-03-20 15:51
Awesome, thanks @htmgarcia 

Visual question ... With 5 across, how does that work on smaller screens?

A second visual question ... Any ideas on the box / green check / red X problem?

The bigger picture is we can remove most right sidebar with @agapetry's help. The bottom 3 boxes should go to a "Settings" area. The "Related Permissions Plugins" can go.

**Comment by htmgarcia** [comment] 2020-03-20 15:56
@stevejburge 
> Visual question ... With 5 across, how does that work on smaller screens?
RE: I'll change that to make it more like "Members" plugin style. 
> Any ideas on the box / green check / red X problem?
RE:  This is still in my radar. 

Please note the left side content will be longer, so the right sidebar won't look that long in comparison.

**Comment by stevejburge** [comment] 2020-03-20 15:59
Thanks @htmgarcia 

And its OK if we do this in stages.

We don't need a 100% overhaul with the first update.

By the way, I like the move to purple buttons for "Save". We can keep yellow for "buy".

**Comment by htmgarcia** [comment] 2020-03-20 16:10
@stevejburge understood.

Currently I have a couple of important things to fix.

1. The first 3 tabs and its contents needs to be fixed to be consistent with the rest of the tabs and its contents:
<img width="942" alt="Screen Shot 2020-03-21 at 1 03 34" src="https://user-images.githubusercontent.com/4999794/77182374-01ad3a00-6b10-11ea-8e43-a1b282e5f208.png">

2. I disabled the PublishPress footer because is broken with the new layout (a CSS issue with alignment). 

Current look in medium and smallest devices:
![screencapture-localhost-8888-wp-wp-admin-admin-php-2020-03-21-01_07_27](https://user-images.githubusercontent.com/4999794/77182698-84ce9000-6b10-11ea-8156-d7556d4e8ac6.png)

![screencapture-localhost-8888-wp-wp-admin-admin-php-2020-03-21-01_07_56](https://user-images.githubusercontent.com/4999794/77182726-8d26cb00-6b10-11ea-8ae4-9b34be6359ad.png)

**Comment by stevejburge** [comment] 2020-03-20 16:13
Thanks @htmgarcia 

I think we should move away from the 5-column

It might take a while, but 1-column might be more manageable

**Comment by agapetry** [comment] 2020-03-20 17:36
@htmgarcia @stevejburge  I don't think converting Post Editing / Deletion / Reading capabilities to separate tabs would be an improvement.  If that grid needs to be split up, it would be better to have a separate tab for each post type.  However, I think a lot of users like the combined grid that allows you to review post capabilities for all post types in an organized way.  I see the benefit of moving the other sections to a tabbed view, but it seems like going to drag Editing / Deletion / Reading into that without enough consideration.

Another element that has to be worked into the design is the custom status permissions provided by Capabilities Pro (when PublishPress and PublishPress Permissions are active with the Permissions "Status Control" module"):

![image](https://user-images.githubusercontent.com/43488774/77190511-c4b15b00-6aaf-11ea-9ac2-d1c54807137e.png)

**Comment by agapetry** [comment] 2020-03-20 17:45
@htmgarcia You should also be aware that checkboxes in the Editing / Deletion / Reading grid get and additional css class when the capability is granted implicitly by the Permissions plugin (through type-specific Supplemental Role granted to the WP Role group.  This is currently represented by a green background around the checkbox:

![image](https://user-images.githubusercontent.com/43488774/77191039-b44db000-6ab0-11ea-82e3-85b3793be2b0.png)

**Comment by agapetry** [comment] 2020-03-20 17:54
Functionally, the main distinction between PublishPress Capabilities and Members is that our plugin customizes not only capability assignment, but also capability enforcement.  Changing the "Type-Specific Capabilities" selections affects which capabilities WordPress imposes, and therefore which checkboxes are available in the Post capabilities grid.  If we flatten the capability checkboxes to an unordered single column and move the "Type-Specific" settings to a different screen, configuration status and possibilities will become harder to visualize.  If cleaning up the screen is the main goal, how about some type of show/hide functionality for those sidebar settings?

**Comment by htmgarcia** [comment] 2020-03-23 13:14
@agapetry I need to admit my knowledge is limited about the best approach on the organization for the permissions checkboxes. I'll fix the display of the editing, deleting and reading tabs and content display (keeping the current column structure) to be consistent with the rest of tabs/content. 

Sorry. This part is not clear to me:

> You should also be aware that checkboxes in the Editing / Deletion / Reading grid get and additional css class when the capability is granted implicitly by the Permissions plugin (through type-specific Supplemental Role granted to the WP Role group. This is currently represented by a green background around the checkbox

**Comment by htmgarcia** [comment] 2020-03-23 14:35
@agapetry is "Role level" correctly located inside "Invalid capabilities"?
<img width="941" alt="Screen Shot 2020-03-23 at 23 34 48" src="https://user-images.githubusercontent.com/4999794/77327752-fe5bbd80-6d5e-11ea-905b-fce0411c0044.png">

**Comment by htmgarcia** [comment] 2020-03-23 16:32
@stevejburge @agapetry reading, deleting, editing looks a little better now in mobile and desktop
<img width="591" alt="Screen Shot 2020-03-24 at 1 31 31" src="https://user-images.githubusercontent.com/4999794/77339547-47b40900-6d6f-11ea-97a9-3de21cdc15e5.png">

**Comment by agapetry** [comment] 2020-03-23 20:55
@htmgarcia Role Level should be in the WordPress Capabilities tab.  The significance of its current location is only that it's on the bottom of the screen.

**Comment by stevejburge** [comment] 2020-03-23 20:57
We do have an issue that suggests removing it from here: https://github.com/publishpress/PublishPress-Capabilities/issues/17

We could perhaps move this to the sidebar for now? That way it doesn't clutter up the main screen

**Comment by agapetry** [comment] 2020-03-23 20:58
@stevejburge Role level on the sidebar would be fine. It should probably be on the bottom: only there for those who look for it.

**Comment by agapetry** [comment] 2020-03-23 22:10
@htmgarcia 

WordPress Roles can also be modified by our PublishPress Permissions plugin.  In that case, capabilities which the role has implicitly are indicated by a green background around the checkbox.

This styling is applied by the "cm-has-via-pp" class:

`td.cm-has-via-pp {
background-color: #84fb84;
}`

![screenshot-10](https://user-images.githubusercontent.com/43488774/77367404-647d1c00-6d30-11ea-96f1-95ef4e475264.png)

> 
> Sorry. This part is not clear to me:
> 
> > You should also be aware that checkboxes in the Editing / Deletion / Reading grid get and additional css class when the capability is granted implicitly by the Permissions plugin (through type-specific Supplemental Role granted to the WP Role group. This is currently represented by a green background around the checkbox

**Comment by htmgarcia** [comment] 2020-03-24 12:20
@agapetry thanks for the clarification. Based on your feedback and suggestions, it would be better to keep read, delete and edit capabilities as regular boxes, and below the rest organized as tabs?

**Comment by stevejburge** [comment] 2020-07-27 20:58
Related: 
https://github.com/publishpress/PublishPress-Capabilities/issues/9

**Comment by htmgarcia** [comment] 2021-08-19 15:57
[The branch ](https://github.com/publishpress/PublishPress-Capabilities/tree/issue-32)where I worked these changes is more than a year old. Maybe better start from scratch.

**Comment by htmgarcia** [comment] 2021-08-19 15:59
@agapetry which branch should I use as base to create a new branch to work on this issue? perhaps "development"?

**Comment by htmgarcia** [comment] 2021-08-24 20:19
@agapetry @stevejburge new starter proposal: https://github.com/publishpress/PublishPress-Capabilities/commit/6d4c859b6cd8f3cc16084a432767653c6c7500c4
<img width="1418" alt="Screen Shot 2021-08-24 at 15 18 09" src="https://user-images.githubusercontent.com/4999794/130684075-fa6fabdd-025b-4d5f-a48e-1c5ab70aec78.png">
<img width="710" alt="Screen Shot 2021-08-24 at 15 17 35" src="https://user-images.githubusercontent.com/4999794/130684085-e67b738e-527f-4f78-bf3d-afd0103cc217.png">
The content section needs some design touches, in particular for the first 3 tabs.

**Comment by stevejburge** [comment] 2021-08-24 20:25
Thanks @htmgarcia. I think this could be good first step to cleaning up this screen.

For "Other WordPress Core Capabilities" and those areas, should we stick with 5 columns? Or use a design that is more like "Admin Menus"?

**Comment by htmgarcia** [comment] 2021-08-24 20:34
@stevejburge not sure if is possible due the states for each capability are 3: checked, unchecked, disabled.
![Screen Shot 2021-08-24 at 15 33 27](https://user-images.githubusercontent.com/4999794/130686132-1d8d2fa4-79dd-4dab-b554-83b22506efdb.png)

**Comment by stevejburge** [comment] 2021-08-24 21:20
@htmgarcia Would it be as simple as keeping checked, unchecked, disabled, but showing them vertically?

**Comment by htmgarcia** [comment] 2021-08-24 21:47
@stevejburge that's possible.

**Comment by stevejburge** [comment] 2021-08-24 23:09
@htmgarcia Thanks. Yes, let's try please. This screen doesn't look like the other screens in the plugin

**Comment by htmgarcia** [comment] 2021-08-24 23:24
@agapetry there is a mention of `cme_form-rows` option to define the number of columns for capabilities. Default is 5. I don't see a place to configure neither a record on database. 
May you confirm if there is no conflict if I force to be 1 column always?
https://github.com/publishpress/PublishPress-Capabilities/blob/development/includes/admin.php#L545

**Comment by agapetry** [comment] 2021-08-25 03:34
@htmgarcia If you guys want to take it to single column, that code would ideally be simplified to eliminate the $checks_per_row variable.  However, I just confirmed that setting $checks_per_row to 1 works without any conflicts.

**Comment by htmgarcia** [comment] 2021-11-01 21:20
Closing since PR has been merged.

**Closed by htmgarcia** 2021-11-01 21:20 UTC
