### ISSUE TITLE
Add a new setting to disable Code Editor in Posts

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Capabilities#298] opened 2021-08-10 20:41 UTC
`settings.codeEditingEnabled = false`

**Comment by olatechpro** [comment] 2022-02-21 12:15
@stevejburge Capabilities Editor features mainly allow user to hide Editor content. So, i'm wondering how you plan for introduction of this feature, category it'll be added and label we'll be giving this to avoid impression of it been option to hide items just like others ?

**Comment by olatechpro** [comment] 2022-02-21 12:27
Also, i noticed the issue is assigned to @htmgarcia but not sure if it's because it was moved from Blocks or i should ignore the issue ? @stevejburge

**Comment by stevejburge** [comment] 2022-02-21 18:21
@htmgarcia @olatechpro I wonder if we can combine this with https://github.com/publishpress/PublishPress-Capabilities/issues/276 ?

@olatechpro This will probably be yours, please

**Comment by olatechpro** [comment] 2022-03-30 10:33
@stevejburge if we're adding this to role, which tab are we placing it?

**Comment by olatechpro** [comment] 2022-03-30 15:57
Frome valentin

```
add_filter('block_editor_settings_all', array($this, 'disableCodeEditor'), 9999);
public function disableCodeEditor($settings) {
    $settings['codeEditingEnabled'] = false;
    return $settings;
}
```

**Comment by stevejburge** [comment] 2022-03-31 17:21
I'm moving this to after the Roles launch also https://github.com/publishpress/PublishPress-Capabilities/issues/276

**Comment by stevejburge** [comment] 2022-04-29 12:53
@olatechpro I think this could be part of tab when you edit user roles via the "Roles" screen: https://github.com/publishpress/PublishPress-Capabilities/issues/276

For example, when you select "Gutenberg" perhaps this becomes an extra option

**Comment by olatechpro** [comment] 2022-05-24 17:58
@stevejburge i don't see reasons why the logic of selecting Gutenberg been the determinant on if this settings will be display or not. Maybe it would have been understandable if we're not allowing multiple options for editor.

**Comment by olatechpro** [comment] 2022-05-24 17:59
@stevejburge this issue also has a pro label. So, confirming if this is pro only field or both?

**Closed** 2022-06-02 09:50 UTC
Labels: Admin Interface
